// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Website_clothing.Models;

#nullable disable

namespace Website_clothing.Migrations
{
    [DbContext(typeof(Website_clothing_DbContext))]
    partial class Website_clothing_DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CTSanPhamKichCo", b =>
                {
                    b.Property<Guid>("cTSanPhamsID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("kichCosID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("cTSanPhamsID", "kichCosID");

                    b.HasIndex("kichCosID");

                    b.ToTable("CTSanPhamKichCo");
                });

            modelBuilder.Entity("CTSanPhamMauSac", b =>
                {
                    b.Property<Guid>("MauSacsID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("cTSanPhamsID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MauSacsID", "cTSanPhamsID");

                    b.HasIndex("cTSanPhamsID");

                    b.ToTable("CTSanPhamMauSac");
                });

            modelBuilder.Entity("CTSanPhamVoucher", b =>
                {
                    b.Property<Guid>("CTSanPhamsID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("vouchersID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CTSanPhamsID", "vouchersID");

                    b.HasIndex("vouchersID");

                    b.ToTable("CTSanPhamVoucher");
                });

            modelBuilder.Entity("HoaDonVoucher", b =>
                {
                    b.Property<Guid>("HoaDonsID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VouchersID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("HoaDonsID", "VouchersID");

                    b.HasIndex("VouchersID");

                    b.ToTable("HoaDonVoucher");
                });

            modelBuilder.Entity("Website_clothing.Models.CTGioHang", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GioHangID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdCTSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<double>("TongTien")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("GioHangID");

                    b.HasIndex("IdCTSanPham");

                    b.ToTable("CTGioHangs");
                });

            modelBuilder.Entity("Website_clothing.Models.CTHoaDon", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<Guid>("IdCTSP")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("IdHoaDon");

                    b.ToTable("CtHoadons");
                });

            modelBuilder.Entity("Website_clothing.Models.CTSanPham", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<double>("GiaBan")
                        .HasColumnType("float");

                    b.Property<Guid>("IDChatLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IDDanhGia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDGiamGia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDKichCo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDMauSac")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDVoucher")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IDChatLieu");

                    b.HasIndex("IDGiamGia");

                    b.HasIndex("IDHang");

                    b.HasIndex("IDSanPham")
                        .IsUnique();

                    b.ToTable("CtSanPhams");
                });

            modelBuilder.Entity("Website_clothing.Models.ChatLieu", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("chatlieus");
                });

            modelBuilder.Entity("Website_clothing.Models.DanhGia", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BinhLuan")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime");

                    b.Property<int>("Sao")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("DanhGias");
                });

            modelBuilder.Entity("Website_clothing.Models.DanhMucSanPham", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("DanhMucSanPhams");
                });

            modelBuilder.Entity("Website_clothing.Models.DoiTra", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("HanDoi")
                        .HasColumnType("datetime");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("NgayDoiTra")
                        .HasColumnType("datetime");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("IdHoaDon")
                        .IsUnique();

                    b.HasIndex("IdSanPham");

                    b.ToTable("doiTras");
                });

            modelBuilder.Entity("Website_clothing.Models.GiamGia", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("GiaTri")
                        .HasColumnType("float");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayApDung")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("GiamGias");
                });

            modelBuilder.Entity("Website_clothing.Models.GioHang", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("Website_clothing.Models.Hang", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Hangs");
                });

            modelBuilder.Entity("Website_clothing.Models.HoaDon", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("IDCTHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDVoucher")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("NgayNhanHang")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime");

                    b.Property<string>("PTThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("char(15)");

                    b.Property<string>("TenNgNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("TienShip")
                        .HasColumnType("float");

                    b.Property<double>("TongTien")
                        .HasColumnType("float");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("IDKhachHang");

                    b.HasIndex("IDNhanVien");

                    b.ToTable("hoadons");
                });

            modelBuilder.Entity("Website_clothing.Models.KhachHang", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Diem")
                        .HasColumnType("float");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("char(15)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("Website_clothing.Models.KichCo", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("KichCos");
                });

            modelBuilder.Entity("Website_clothing.Models.LichSuMuaHang", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IDHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IDKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IDHoaDon")
                        .IsUnique()
                        .HasFilter("[IDHoaDon] IS NOT NULL");

                    b.HasIndex("IDKhachHang");

                    b.ToTable("lichSuMuaHangs");
                });

            modelBuilder.Entity("Website_clothing.Models.LichSuTichDiem", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Diem")
                        .HasColumnType("float");

                    b.Property<Guid?>("IDHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDQuyDoiDiem")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("IDHoaDon")
                        .IsUnique()
                        .HasFilter("[IDHoaDon] IS NOT NULL");

                    b.HasIndex("IDKhachHang");

                    b.HasIndex("IDQuyDoiDiem");

                    b.ToTable("LichSuTichDiems");
                });

            modelBuilder.Entity("Website_clothing.Models.MauSac", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TenMauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("mauSacs");
                });

            modelBuilder.Entity("Website_clothing.Models.NhanVien", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("IDRole")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("IDRole");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("Website_clothing.Models.QuyDoiDiem", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TiLeTichDiem")
                        .HasColumnType("real");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("QuyDoiDiems");
                });

            modelBuilder.Entity("Website_clothing.Models.Role", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Website_clothing.Models.SanPham", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Anh")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<double>("Gia")
                        .HasColumnType("float");

                    b.Property<Guid>("IDDanhMucSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("IDDanhMucSanPham");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("Website_clothing.Models.Voucher", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DieuKien")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("GiaTri")
                        .HasColumnType("float");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("NgayApDung")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("trangthai")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("vouchers");
                });

            modelBuilder.Entity("CTSanPhamKichCo", b =>
                {
                    b.HasOne("Website_clothing.Models.CTSanPham", null)
                        .WithMany()
                        .HasForeignKey("cTSanPhamsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Website_clothing.Models.KichCo", null)
                        .WithMany()
                        .HasForeignKey("kichCosID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CTSanPhamMauSac", b =>
                {
                    b.HasOne("Website_clothing.Models.MauSac", null)
                        .WithMany()
                        .HasForeignKey("MauSacsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Website_clothing.Models.CTSanPham", null)
                        .WithMany()
                        .HasForeignKey("cTSanPhamsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CTSanPhamVoucher", b =>
                {
                    b.HasOne("Website_clothing.Models.CTSanPham", null)
                        .WithMany()
                        .HasForeignKey("CTSanPhamsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Website_clothing.Models.Voucher", null)
                        .WithMany()
                        .HasForeignKey("vouchersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HoaDonVoucher", b =>
                {
                    b.HasOne("Website_clothing.Models.HoaDon", null)
                        .WithMany()
                        .HasForeignKey("HoaDonsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Website_clothing.Models.Voucher", null)
                        .WithMany()
                        .HasForeignKey("VouchersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Website_clothing.Models.CTGioHang", b =>
                {
                    b.HasOne("Website_clothing.Models.GioHang", "GioHang")
                        .WithMany("cTGioHangs")
                        .HasForeignKey("GioHangID");

                    b.HasOne("Website_clothing.Models.CTSanPham", "CTSanPhams")
                        .WithMany("CTGioHang")
                        .HasForeignKey("IdCTSanPham");

                    b.Navigation("CTSanPhams");

                    b.Navigation("GioHang");
                });

            modelBuilder.Entity("Website_clothing.Models.CTHoaDon", b =>
                {
                    b.HasOne("Website_clothing.Models.HoaDon", "HoaDon")
                        .WithMany("CTHoaDons")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("Website_clothing.Models.CTSanPham", b =>
                {
                    b.HasOne("Website_clothing.Models.ChatLieu", "ChatLieu")
                        .WithMany("CTSanPhams")
                        .HasForeignKey("IDChatLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Website_clothing.Models.GiamGia", "GiamGia")
                        .WithMany("CTSanPhams")
                        .HasForeignKey("IDGiamGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Website_clothing.Models.Hang", "hang")
                        .WithMany("ctsanphams")
                        .HasForeignKey("IDHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Website_clothing.Models.SanPham", "sanpham")
                        .WithOne("ctsanpham")
                        .HasForeignKey("Website_clothing.Models.CTSanPham", "IDSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatLieu");

                    b.Navigation("GiamGia");

                    b.Navigation("hang");

                    b.Navigation("sanpham");
                });

            modelBuilder.Entity("Website_clothing.Models.DanhGia", b =>
                {
                    b.HasOne("Website_clothing.Models.CTSanPham", "CTSanPhams")
                        .WithMany("DanhGias")
                        .HasForeignKey("ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CTSanPhams");
                });

            modelBuilder.Entity("Website_clothing.Models.DoiTra", b =>
                {
                    b.HasOne("Website_clothing.Models.HoaDon", "HoaDon")
                        .WithOne("DoiTra")
                        .HasForeignKey("Website_clothing.Models.DoiTra", "IdHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Website_clothing.Models.SanPham", "SanPham")
                        .WithMany("DoiTras")
                        .HasForeignKey("IdSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("Website_clothing.Models.HoaDon", b =>
                {
                    b.HasOne("Website_clothing.Models.KhachHang", "KhachHang")
                        .WithMany("hoaDons")
                        .HasForeignKey("IDKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Website_clothing.Models.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("IDNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Website_clothing.Models.KhachHang", b =>
                {
                    b.HasOne("Website_clothing.Models.GioHang", "GioHang")
                        .WithOne("KhachHang")
                        .HasForeignKey("Website_clothing.Models.KhachHang", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GioHang");
                });

            modelBuilder.Entity("Website_clothing.Models.LichSuMuaHang", b =>
                {
                    b.HasOne("Website_clothing.Models.HoaDon", "HoaDon")
                        .WithOne("LichSuMuaHang")
                        .HasForeignKey("Website_clothing.Models.LichSuMuaHang", "IDHoaDon");

                    b.HasOne("Website_clothing.Models.KhachHang", "KhachHang")
                        .WithMany("lichSuMuaHangs")
                        .HasForeignKey("IDKhachHang");

                    b.Navigation("HoaDon");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("Website_clothing.Models.LichSuTichDiem", b =>
                {
                    b.HasOne("Website_clothing.Models.HoaDon", "HoaDon")
                        .WithOne("LichSuTichDiem")
                        .HasForeignKey("Website_clothing.Models.LichSuTichDiem", "IDHoaDon");

                    b.HasOne("Website_clothing.Models.KhachHang", "KhachHang")
                        .WithMany("lichSuTichDiems")
                        .HasForeignKey("IDKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Website_clothing.Models.QuyDoiDiem", "QuyDoiDiem")
                        .WithMany("LichSuTichDiems")
                        .HasForeignKey("IDQuyDoiDiem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("KhachHang");

                    b.Navigation("QuyDoiDiem");
                });

            modelBuilder.Entity("Website_clothing.Models.NhanVien", b =>
                {
                    b.HasOne("Website_clothing.Models.Role", "Role")
                        .WithMany("NhanViens")
                        .HasForeignKey("IDRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Website_clothing.Models.SanPham", b =>
                {
                    b.HasOne("Website_clothing.Models.DanhMucSanPham", "DanhMucSanPham")
                        .WithMany("SanPhams")
                        .HasForeignKey("IDDanhMucSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMucSanPham");
                });

            modelBuilder.Entity("Website_clothing.Models.CTSanPham", b =>
                {
                    b.Navigation("CTGioHang");

                    b.Navigation("DanhGias");
                });

            modelBuilder.Entity("Website_clothing.Models.ChatLieu", b =>
                {
                    b.Navigation("CTSanPhams");
                });

            modelBuilder.Entity("Website_clothing.Models.DanhMucSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("Website_clothing.Models.GiamGia", b =>
                {
                    b.Navigation("CTSanPhams");
                });

            modelBuilder.Entity("Website_clothing.Models.GioHang", b =>
                {
                    b.Navigation("KhachHang");

                    b.Navigation("cTGioHangs");
                });

            modelBuilder.Entity("Website_clothing.Models.Hang", b =>
                {
                    b.Navigation("ctsanphams");
                });

            modelBuilder.Entity("Website_clothing.Models.HoaDon", b =>
                {
                    b.Navigation("CTHoaDons");

                    b.Navigation("DoiTra");

                    b.Navigation("LichSuMuaHang");

                    b.Navigation("LichSuTichDiem");
                });

            modelBuilder.Entity("Website_clothing.Models.KhachHang", b =>
                {
                    b.Navigation("hoaDons");

                    b.Navigation("lichSuMuaHangs");

                    b.Navigation("lichSuTichDiems");
                });

            modelBuilder.Entity("Website_clothing.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Website_clothing.Models.QuyDoiDiem", b =>
                {
                    b.Navigation("LichSuTichDiems");
                });

            modelBuilder.Entity("Website_clothing.Models.Role", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("Website_clothing.Models.SanPham", b =>
                {
                    b.Navigation("DoiTras");

                    b.Navigation("ctsanpham");
                });
#pragma warning restore 612, 618
        }
    }
}
